# config/_default/languages.zh-cn.toml

title = "JHY"

[params.author]
name = "JHY"
image = "img/author.jpg"
headline = "Undergraduate, Software Instisude, NJU"
bio = "实迷途其未远，觉今是而昨非。"
links = [
  { github = "https://github.com/549w" }
]