# config/_default/languages.zh-cn.toml

title = "Hi, I'm JHY"

[params.author]
name = "Hongyu Jiang"
image = "img/author.jpg"
headline = "Undergraduate, Software Instisude, NanJing University"
email = "hi@imjhy.com"
bio = "实迷途其未远，觉今是而昨非。"
links = [
  { github = "https://github.com/549w" }
]