baseURL = "https://549w.github.io/"
languageCode = "zh-cn"
title = "Jhy's Blog"

theme = "PaperMod"

[params]
author = "Jhy"

defaultTheme = "auto"

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true

[menu]

[[menu.main]]
name = "文章"
url = "/posts/"
weight = 1

[[menu.main]]
name = "关于"
url = "/about/"
weight = 2